// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"com.alex.infosys/app/dal/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newPeasantDatum(db *gorm.DB) peasantDatum {
	_peasantDatum := peasantDatum{}

	_peasantDatum.peasantDatumDo.UseDB(db)
	_peasantDatum.peasantDatumDo.UseModel(&model.PeasantDatum{})

	tableName := _peasantDatum.peasantDatumDo.TableName()
	_peasantDatum.ALL = field.NewField(tableName, "*")
	_peasantDatum.ID = field.NewInt32(tableName, "id")
	_peasantDatum.UserID = field.NewInt64(tableName, "user_id")
	_peasantDatum.Name = field.NewString(tableName, "name")
	_peasantDatum.Gender = field.NewField(tableName, "gender")
	_peasantDatum.Address = field.NewString(tableName, "address")
	_peasantDatum.Idcard = field.NewString(tableName, "idcard")
	_peasantDatum.CreateAt = field.NewTime(tableName, "create_at")
	_peasantDatum.UpdateAt = field.NewTime(tableName, "update_at")
	_peasantDatum.DeletedAt = field.NewField(tableName, "deleted_at")

	_peasantDatum.fillFieldMap()

	return _peasantDatum
}

type peasantDatum struct {
	peasantDatumDo

	ALL       field.Field
	ID        field.Int32
	UserID    field.Int64
	Name      field.String
	Gender    field.Field
	Address   field.String
	Idcard    field.String
	CreateAt  field.Time
	UpdateAt  field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (p peasantDatum) Table(newTableName string) *peasantDatum {
	p.peasantDatumDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p peasantDatum) As(alias string) *peasantDatum {
	p.peasantDatumDo.DO = *(p.peasantDatumDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *peasantDatum) updateTableName(table string) *peasantDatum {
	p.ALL = field.NewField(table, "*")
	p.ID = field.NewInt32(table, "id")
	p.UserID = field.NewInt64(table, "user_id")
	p.Name = field.NewString(table, "name")
	p.Gender = field.NewField(table, "gender")
	p.Address = field.NewString(table, "address")
	p.Idcard = field.NewString(table, "idcard")
	p.CreateAt = field.NewTime(table, "create_at")
	p.UpdateAt = field.NewTime(table, "update_at")
	p.DeletedAt = field.NewField(table, "deleted_at")

	p.fillFieldMap()

	return p
}

func (p *peasantDatum) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *peasantDatum) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["user_id"] = p.UserID
	p.fieldMap["name"] = p.Name
	p.fieldMap["gender"] = p.Gender
	p.fieldMap["address"] = p.Address
	p.fieldMap["idcard"] = p.Idcard
	p.fieldMap["create_at"] = p.CreateAt
	p.fieldMap["update_at"] = p.UpdateAt
	p.fieldMap["deleted_at"] = p.DeletedAt
}

func (p peasantDatum) clone(db *gorm.DB) peasantDatum {
	p.peasantDatumDo.ReplaceDB(db)
	return p
}

type peasantDatumDo struct{ gen.DO }

func (p peasantDatumDo) Debug() *peasantDatumDo {
	return p.withDO(p.DO.Debug())
}

func (p peasantDatumDo) WithContext(ctx context.Context) *peasantDatumDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p peasantDatumDo) Clauses(conds ...clause.Expression) *peasantDatumDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p peasantDatumDo) Returning(value interface{}, columns ...string) *peasantDatumDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p peasantDatumDo) Not(conds ...gen.Condition) *peasantDatumDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p peasantDatumDo) Or(conds ...gen.Condition) *peasantDatumDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p peasantDatumDo) Select(conds ...field.Expr) *peasantDatumDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p peasantDatumDo) Where(conds ...gen.Condition) *peasantDatumDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p peasantDatumDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *peasantDatumDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p peasantDatumDo) Order(conds ...field.Expr) *peasantDatumDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p peasantDatumDo) Distinct(cols ...field.Expr) *peasantDatumDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p peasantDatumDo) Omit(cols ...field.Expr) *peasantDatumDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p peasantDatumDo) Join(table schema.Tabler, on ...field.Expr) *peasantDatumDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p peasantDatumDo) LeftJoin(table schema.Tabler, on ...field.Expr) *peasantDatumDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p peasantDatumDo) RightJoin(table schema.Tabler, on ...field.Expr) *peasantDatumDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p peasantDatumDo) Group(cols ...field.Expr) *peasantDatumDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p peasantDatumDo) Having(conds ...gen.Condition) *peasantDatumDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p peasantDatumDo) Limit(limit int) *peasantDatumDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p peasantDatumDo) Offset(offset int) *peasantDatumDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p peasantDatumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *peasantDatumDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p peasantDatumDo) Unscoped() *peasantDatumDo {
	return p.withDO(p.DO.Unscoped())
}

func (p peasantDatumDo) Create(values ...*model.PeasantDatum) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p peasantDatumDo) CreateInBatches(values []*model.PeasantDatum, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p peasantDatumDo) Save(values ...*model.PeasantDatum) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p peasantDatumDo) First() (*model.PeasantDatum, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PeasantDatum), nil
	}
}

func (p peasantDatumDo) Take() (*model.PeasantDatum, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PeasantDatum), nil
	}
}

func (p peasantDatumDo) Last() (*model.PeasantDatum, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PeasantDatum), nil
	}
}

func (p peasantDatumDo) Find() ([]*model.PeasantDatum, error) {
	result, err := p.DO.Find()
	return result.([]*model.PeasantDatum), err
}

func (p peasantDatumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PeasantDatum, err error) {
	buf := make([]*model.PeasantDatum, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p peasantDatumDo) FindInBatches(result *[]*model.PeasantDatum, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p peasantDatumDo) Attrs(attrs ...field.AssignExpr) *peasantDatumDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p peasantDatumDo) Assign(attrs ...field.AssignExpr) *peasantDatumDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p peasantDatumDo) Joins(field field.RelationField) *peasantDatumDo {
	return p.withDO(p.DO.Joins(field))
}

func (p peasantDatumDo) Preload(field field.RelationField) *peasantDatumDo {
	return p.withDO(p.DO.Preload(field))
}

func (p peasantDatumDo) FirstOrInit() (*model.PeasantDatum, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PeasantDatum), nil
	}
}

func (p peasantDatumDo) FirstOrCreate() (*model.PeasantDatum, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PeasantDatum), nil
	}
}

func (p peasantDatumDo) FindByPage(offset int, limit int) (result []*model.PeasantDatum, count int64, err error) {
	if limit <= 0 {
		count, err = p.Count()
		return
	}

	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p peasantDatumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p *peasantDatumDo) withDO(do gen.Dao) *peasantDatumDo {
	p.DO = *do.(*gen.DO)
	return p
}
