// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrgnizationType = "orgnization_type"

// OrgnizationType mapped from table <orgnization_type>
type OrgnizationType struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TypeName  string    `gorm:"column:type_name" json:"type_name"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName OrgnizationType's table name
func (*OrgnizationType) TableName() string {
	return TableNameOrgnizationType
}
