// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePeasentPlant = "peasent_plant"

// PeasentPlant mapped from table <peasent_plant>
type PeasentPlant struct {
	ID        int32          `gorm:"column:id;primaryKey" json:"id"`
	Area      float64        `gorm:"column:area" json:"area"`
	PlantType string         `gorm:"column:plant_type" json:"plant_type"`
	PeasentID int32          `gorm:"column:peasent_id" json:"peasent_id"`
	CreateAt  time.Time      `gorm:"column:create_at" json:"create_at"`
	UpdateAt  time.Time      `gorm:"column:update_at" json:"update_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName PeasentPlant's table name
func (*PeasentPlant) TableName() string {
	return TableNamePeasentPlant
}
