// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDictionary = "sys_dictionary"

// SysDictionary mapped from table <sys_dictionary>
type SysDictionary struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Lable     string    `gorm:"column:lable" json:"lable"`
	Value     string    `gorm:"column:value" json:"value"`
	Pid       int32     `gorm:"column:pid" json:"pid"`
	Path      string    `gorm:"column:path" json:"path"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName SysDictionary's table name
func (*SysDictionary) TableName() string {
	return TableNameSysDictionary
}
