// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_user"

// SysUser mapped from table <sys_user>
type SysUser struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserName      string         `gorm:"column:user_name" json:"user_name"`
	Password      string         `gorm:"column:password" json:"password"`
	Phone         string         `gorm:"column:phone" json:"phone"`
	RealName      string         `gorm:"column:real_name" json:"real_name"`
	Pid           int64          `gorm:"column:pid" json:"pid"`
	RoleID        string         `gorm:"column:role_id" json:"role_id"` // 厂库管理人员， 佳慧管理人员， 技术指导员， 农户 ，基层社人员
	Idcard        string         `gorm:"column:idcard" json:"idcard"`
	OrgnicationID int32          `gorm:"column:orgnication_id" json:"orgnication_id"`
	CreateAt      time.Time      `gorm:"column:create_at" json:"create_at"`
	UpdateAt      time.Time      `gorm:"column:update_at" json:"update_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreateBy      int32          `gorm:"column:create_by" json:"create_by"`
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
