basePath: /api/cms
definitions:
  PageQuery:
    properties:
      current:
        type: integer
      pageSize:
        type: integer
      query:
        $ref: '#/definitions/g.MapStrAny'
        type: object
      sorts:
        $ref: '#/definitions/g.MapStrStr'
        type: object
    type: object
  Response:
    properties:
      data:
        type: object
      message:
        type: string
      statusCode:
        type: integer
      success:
        type: boolean
      total:
        type: integer
    type: object
  g.MapStrAny:
    additionalProperties: true
    type: object
  g.MapStrStr:
    additionalProperties:
      type: string
    type: object
  model.OrgnizationType:
    properties:
      created_at:
        type: string
      id:
        type: integer
      type_name:
        type: string
      updated_at:
        type: string
    type: object
  model.SysDictionary:
    properties:
      created_at:
        type: string
      id:
        type: integer
      lable:
        type: string
      path:
        type: string
      pid:
        type: integer
      updated_at:
        type: string
      value:
        type: string
    type: object
  model.SysOrgnization:
    properties:
      contact_addres:
        type: string
      contact_name:
        type: string
      contact_phone:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      ext1:
        type: string
      ext2:
        type: string
      ext3:
        type: string
      ext4:
        type: string
      ext5:
        type: string
      ext6:
        type: string
      ext7:
        type: string
      ext8:
        type: string
      ext9:
        type: string
      ext10:
        type: string
      id:
        type: integer
      name:
        type: string
      p_key:
        description: 权限标识
        type: string
      p_name:
        description: 权限名称
        type: string
      pid:
        type: string
      type_id:
        type: integer
      updated_at:
        type: string
    type: object
  model.SysRole:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      desc:
        type: string
      id:
        type: integer
      key:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
  license: {}
  title: gin cms api
  version: 0.0.1
paths:
  /api/system/dic/query:
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/PageQuery'
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            $ref: '#/definitions/Response'
      summary: 系统数据字典
      tags:
      - dictionary
  /api/system/dic/updates:
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/model.SysDictionary'
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            $ref: '#/definitions/Response'
      summary: 系统数据字典
      tags:
      - dictionary
  /api/system/orgs/query:
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/PageQuery'
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            allOf:
            - $ref: '#/definitions/Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.SysOrgnization'
                  type: array
              type: object
      summary: 组织机构
      tags:
      - organization
  /api/system/orgs/type/query:
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/PageQuery'
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            $ref: '#/definitions/Response'
      summary: 机构类型
      tags:
      - orgnizationType
  /api/system/orgs/type/updates:
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/model.OrgnizationType'
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            $ref: '#/definitions/Response'
      summary: 机构类型
      tags:
      - orgnizationType
  /api/system/orgs/updates:
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/model.SysOrgnization'
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            $ref: '#/definitions/Response'
      summary: 组织机构
      tags:
      - organization
  /api/system/roles/updates:
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/model.SysRole'
      produces:
      - application/json
      responses:
        "200":
          description: result
          schema:
            $ref: '#/definitions/Response'
      summary: 角色
      tags:
      - SysRole
swagger: "2.0"
